jwt:
    expiration: 6048000
    header: AuthToken
    secret: cripterKey192837465
server:
    port: 8081
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/jtodo?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
    http:
        multipart:
            enabled: false
            max-file-size: -1
            max-request-size: -1
    jpa:
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
